name: Crear video desde noticia

on:
  workflow_dispatch:

jobs:
  generar_video:
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script principal
        run: python main.py

      - name: Subir video generado
        uses: actions/upload-artifact@v3.1.0
        with:
          name: video
          path: video.mp4
